### ISSUE TITLE
EEPROM was not found

### ISSUE THREAD

**Issue by gunaone** [vtl/eeprom_93c86#2]
hy @vtl 
thank for fast the respon.

i was try with the example, but i get "EEPROM was not found"...

do u was try and success?

thanks..

**Comment by vtl** [comment]
Yes, I wrote this code for my other project: https://github.com/vtl/volvo-ddd/ It works fine there.

How did you solder the chip? It should be put into 8 bit mode. If you can't figure out what's wrong, I would advise to capture CS, CLK, DI and DO signals with logic analyzer, it will make it easier to figure out what's wrong.

**Comment by gunaone** [comment]
![image](https://user-images.githubusercontent.com/12540556/45936528-f6905100-bfe1-11e8-80a9-5465a787dc22.png)

i use pin configurations like that image....

actually i dont have logic analyzer, 
thanks @vtl , I will post here if I succeed.

**Comment by vtl** [comment]
What chip is it exactly? Does it need a pull-up resistor on pin 7 (Program Enable)?

**Comment by gunaone** [comment]
hi @vtl i am sory....
ic 93c86wp k325s exactly i use, 
![image](https://user-images.githubusercontent.com/12540556/46651646-e9bb5200-cbca-11e8-950c-f3f8dff6b3f8.png)

i can't find the number 1 of pin, that under the word 93c86wp?correct me....

**Comment by vtl** [comment]
Pin numeration (common across all SOIC/SOP/etc packages):
```
8 7 6 5
1 2 3 4
```

I can't find datasheet for 93C86W**P**. 93C86W is available though.

**Comment by gunaone** [comment]
hy @vtl 

in serial monitor i get
"EEPROM was not found"

how about pin 6, 1 or 0..?

**Comment by vtl** [comment]
Pins numeration starts with 1.

I would suggest to get a logic analyzer and look at what's going go on CS, CLK, DI and DO pins.

**Comment by gunaone** [comment]
CS     1............8   Vcc
CLK   2............7   R10k->Vcc
DI      3............6   *GND*
DO    4............5   GND

hy @vtl , i am sorry because i miss 1 step that is pin 6 to gnd...
is work, thank u very much....
BUT,
the result is 8 bit mode right..
how about 16 bit mode, i don't know to do that's.....

once again thank u very much....

**Comment by vtl** [comment]
The code only works with 8 bit mode. If you were able to get anything from EEPROM, it's 8 bit.
